# @format

name: discord-clone

services:
  postgres:
    image: postgres:13
    container_name: discord-clone-postgres
    hostname: discord-clone-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - discord_clone_postgres:/var/lib/postgresql/data
    networks:
      - discord

  app:
    container_name: app
    hostname: discord-clone-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - discord
    depends_on:
      - postgres

volumes:
  discord_clone_postgres:

networks:
  discord:
    name: discord
    driver: bridge
