# @format

name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Next.js App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf discord-clone
            echo "Pulling the latest code..."
            git clone https://github.com/yusuf-cirak/discord-clone discord-clone

            cd discord-clone

            echo "Creating secret .env file..."

            echo "${{ secrets.DOTENV }}" > .env

            echo "Setting environment variables for deployment script..."

            export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
            export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
            export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"

            bash deploy.sh
